name: Activate Submodules

on: workflow_dispatch
jobs:
  git_reveals:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
      - name: Add submodules
        run: git submodule add -f https://github.com/hakimel/reveal.js.git assets/js/reveal.js
